# Generated by Django 2.1.4 on 2018-12-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(choices=[(1, 'M'), (2, 'F')])),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=100)),
                ('duracao', models.DurationField(default=0)),
                ('link', models.URLField()),
                ('estrelas', models.IntegerField(default=0)),
                ('lancamento', models.DateField()),
                ('elenco', models.ManyToManyField(to='netflix.Ator')),
            ],
            options={
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netflix.Genero'),
        ),
        migrations.AddField(
            model_name='filme',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netflix.Idioma'),
        ),
    ]
