# Generated by Django 2.1.4 on 2018-12-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Produtoras',
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='produtora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netflix.Produtora'),
        ),
    ]
