# Generated by Django 2.1.4 on 2018-12-26 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('netflix', '0003_auto_20181226_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ator',
            name='nome',
        ),
    ]
