# Generated by Django 2.1.4 on 2018-12-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netflix', '0004_remove_ator_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='sexo',
            field=models.CharField(choices=[(1, 'M'), (2, 'F')], max_length=1),
        ),
    ]
